# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qusetion_text',
            new_name='question_text',
        ),
    ]
